### ISSUE TITLE
Add support for computed index properties

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-index-pipelines#199]
We might add support for _computed_ index properties. These properties are not derived from the HTML contents, but from other properties, e.g.
```
properties:
  select: none
  external-path:
    value: |
      replace(path, '/publish/', '/')
```
In order not to change the schema for `helix-query.yaml` (`select` property is mandatory there), I suggest to use the special value `none` to mark a property computed.
