### ISSUE TITLE
implement possibility to index exceprts.

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-index-pipelines#37]
something like:

```
teaser:
 select: '.content',
 value: ${words(0,20)}
```

or 

```
teaser:
 select: '.content',
 value: ${words(text(), 0, 20)}
```

**Comment by tripodsan** [comment]
implemented more holistic approach:

```
  properties:
      teaser:
        select: main > div:nth-last-of-type(-n+3) p
        value: |
          words(textContent(el), 0, 5)
```

see #38 for details.
